# Generated by Django 3.2.2 on 2021-06-03 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.CharField(max_length=100)),
                ('expenseAmount', models.FloatField()),
                ('expenseCategory', models.CharField(max_length=100)),
                ('expenseDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
