# Generated by Django 3.2.2 on 2021-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDesc', models.CharField(max_length=500)),
                ('taskAuthor', models.CharField(max_length=100)),
            ],
        ),
    ]
