# Generated by Django 3.2.2 on 2021-05-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profileImage',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
