# Generated by Django 3.2.2 on 2021-05-22 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0002_userdata_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('createdOn', models.DateField(default=datetime.datetime(2021, 5, 22, 12, 29, 33, 500547))),
                ('coverImage', models.ImageField(default='blogdefault.jpeg', upload_to='blog_images/')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlogApp.userdata')),
            ],
        ),
    ]
