# Generated by Django 3.2.2 on 2021-05-22 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0004_auto_20210522_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 14, 16, 46, 890522)),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profileImage',
            field=models.ImageField(default='default..png', upload_to='profile_images/'),
        ),
    ]
