# Generated by Django 3.2.2 on 2021-06-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookID', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('bookPrice', models.FloatField()),
                ('bookState', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('studentEmailID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoorowedBooks',
            fields=[
                ('borrowID', models.IntegerField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSapp.books')),
                ('stduent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSapp.students')),
            ],
        ),
    ]
