# Generated by Django 3.2.2 on 2021-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phn_no',
            field=models.CharField(max_length=100),
        ),
    ]
