# Generated by Django 3.2.2 on 2021-06-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestID', models.IntegerField(primary_key=True, serialize=False)),
                ('guestFirstName', models.CharField(max_length=100)),
                ('guestLastName', models.CharField(max_length=100)),
                ('guestAddess', models.CharField(max_length=100)),
                ('guestEmailID', models.CharField(max_length=100, unique=True)),
                ('guestPhone', models.CharField(max_length=100)),
                ('guestProfileImage', models.ImageField(default='profileImage/default/', upload_to='profileImage/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('roomStatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('roomStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('roomTypeName', models.CharField(max_length=100)),
                ('roomTypeImage', models.ImageField(default='roomImages/default/', upload_to='roomImages/')),
                ('roomPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.IntegerField(primary_key=True, serialize=False)),
                ('roomStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMapp.roomstatus')),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMapp.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.IntegerField(primary_key=True, serialize=False)),
                ('checkINDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMapp.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMapp.room')),
            ],
        ),
    ]
