# Generated by Django 3.2.2 on 2021-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='noOfAdults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='noOfChildren',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='totolPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
