# Generated by Django 3.2.3 on 2021-05-19 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 12, 35, 3, 892442)),
        ),
    ]
