# Generated by Django 3.2.2 on 2021-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phn_number', models.IntegerField()),
                ('profile_image', models.ImageField(default='Images/default/default.png', upload_to='media/')),
            ],
        ),
    ]
