# Generated by Django 3.2.2 on 2021-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(default='Images/default/default.png', upload_to='media/Images/'),
        ),
    ]
