# Generated by Django 3.2.2 on 2021-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userdata_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(default='Images/default/default.png', upload_to='Images/'),
        ),
    ]
