# Generated by Django 3.2.2 on 2021-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('addess', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='Images/Default/default.png', upload_to='Images/ProfileImage/')),
            ],
        ),
    ]
