# Generated by Django 3.2.2 on 2021-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelGoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightName', models.CharField(max_length=100)),
                ('flightSource', models.CharField(max_length=100)),
                ('flightDest', models.CharField(max_length=100)),
                ('flightDepartureTime', models.TimeField()),
                ('flightArrivalTime', models.TimeField()),
                ('duration', models.TimeField()),
                ('noOfSeats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
